name: Run Daily Python Script

on:
  schedule:
    # Runs at 3:00 AM UTC every day
    - cron: '0 3 * * *'
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        echo "SUPABASE_PORT is set: ${{ env.SUPABASE_PORT != '' }}"
        echo "SUPABASE_URL is set: ${{ env.SUPABASE_URL != '' }}"
        
    - name: Run script
      run: python pipeline.py
      env:
        API_KEY: ${{ secrets.API_KEY }}
        SUPABASE_USER: ${{ secrets.SUPABASE_USER }}
        SUPABASE_PASSWORD: ${{ secrets.SUPABASE_PASSWORD }}
        SUPABASE_HOST: ${{ secrets.SUPABASE_HOST }}
        SUPABASE_PORT: ${{ secrets.SUPABASE_PORT }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        
